// Department actionsTypes

export const DEPARTMENT_GET_DATA = "DEPARTMENT_GET_DATA";
export const DEPARTMENT_SET_DATA = "DEPARTMENT_SET_DATA";
export const DEPARTMENT_FAIL_DATA = "DEPARTMENT_FAIL_DATA";
export const DELETE_DEPARTMENT_FAIL = "DELETE_DEPARTMENT_FAIL";
export const POST_DEPARTMENT_DATA = "POST_DEPARTMENT_DATA";
export const POST_DEPARTMENT_DATA_START = "POST_DEPARTMENT_DATA_START";
export const POST_DEPARTMENT_DATA_FAIL = "POST_DEPARTMENT_DATA_FAIL";
export const EDIT_DEPARTMENT_ROW_START = "EDIT_DEPARTMENT_ROW_START";

export const FAIL_EDIT_DEPARTMENT = "FAIL_EDIT_DEPARTMENT";
export const CURRENT_USER_EDIT_DEPARTMENT = "CURRENT_USER_EDIT_DEPARTMENT";
export const UPDATE_DEPARTMENT_DATA_START = "UPDATE_DEPARTMENT_DATA_START";

// Form ActionTypes

export const FORM_GET_DATA = "FORM_GET_DATA";
export const FORM_SET_DATA = "FORM_SET_DATA";
export const FORM_FAIL_DATA = "FORM_FAIL_DATA";
export const DELETE_FORM_FAIL = "DELETE_FORM_FAIL";
export const POST_FORM_DATA = "POST_FORM_DATA";
export const POST_FORM_DATA_START = "POST_FORM_DATA_START";
export const POST_FORM_DATA_FAIL = "POST_FORM_DATA_FAIL";
export const EDIT_FORM_ROW_START = "EDIT_FORM_ROW_START";

export const FAIL_EDIT_FORM = "FAIL_EDIT_FORM";
export const CURRENT_USER_EDIT_FORM = "CURRENT_USER_EDIT_FORM";
export const UPDATE_FORM_DATA_START = "UPDATE_FORM_DATA_START";

// Prefix actionTypes

export const PREFIX_GET_DATA = "PREFIX_GET_DATA";
export const PREFIX_SET_DATA = "PREFIX_SET_DATA";
export const PREFIX_FAIL_DATA = "PREFIX_FAIL_DATA";
export const DELETE_PREFIX_FAIL = "DELETE_PREFIX_FAIL";
export const POST_PREFIX_DATA = "POST_PREFIX_DATA";
export const POST_PREFIX_DATA_START = "POST_PREFIX_DATA_START";
export const POST_PREFIX_DATA_FAIL = "POST_PREFIX_DATA_FAIL";
export const EDIT_PREFIX_ROW_START = "EDIT_PREFIX_ROW_START";

export const FAIL_EDIT_PREFIX = "FAIL_EDIT_PREFIX";
export const CURRENT_USER_EDIT_PREFIX = "CURRENT_USER_EDIT_PREFIX";
export const UPDATE_PREFIX_DATA_START = "UPDATE_PREFIX_DATA_START";
