//LOGIN
export const ADD_LOGIN = "ADD_LOGIN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REMOVE_LOGIN = "REMOVE_LOGIN";

//Sign up
export const ADD_SIGNUP = "ADD_SIGNUP";
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const REMOVE_SIGNUP = "REMOVE_SIGNUP";

// Department actionsTypes

export const DEPARTMENT_GET_DATA = "DEPARTMENT_GET_DATA";
export const DEPARTMENT_LOADING = "DEPARTMENT_LOADING";
export const DEPARTMENT_SET_DATA = "DEPARTMENT_SET_DATA";
export const DEPARTMENT_FAIL_DATA = "DEPARTMENT_FAIL_DATA";
export const DELETE_DEPARTMENT_FAIL = "DELETE_DEPARTMENT_FAIL";
export const POST_DEPARTMENT_DATA = "POST_DEPARTMENT_DATA";
export const POST_DEPARTMENT_DATA_START = "POST_DEPARTMENT_DATA_START";
export const POST_DEPARTMENT_DATA_FAIL = "POST_DEPARTMENT_DATA_FAIL";
export const EDIT_DEPARTMENT_ROW_START = "EDIT_DEPARTMENT_ROW_START";

export const FAIL_EDIT_DEPARTMENT = "FAIL_EDIT_DEPARTMENT";
export const CURRENT_USER_EDIT_DEPARTMENT = "CURRENT_USER_EDIT_DEPARTMENT";
export const UPDATE_DEPARTMENT_DATA_START = "UPDATE_DEPARTMENT_DATA_START";

// Form ActionTypes

export const FORM_GET_DATA = "FORM_GET_DATA";
export const FORM_SET_DATA = "FORM_SET_DATA";
export const FORM_FAIL_DATA = "FORM_FAIL_DATA";
export const DELETE_FORM_FAIL = "DELETE_FORM_FAIL";
export const POST_FORM_DATA = "POST_FORM_DATA";
export const POST_FORM_DATA_START = "POST_FORM_DATA_START";
export const POST_FORM_DATA_FAIL = "POST_FORM_DATA_FAIL";
export const EDIT_FORM_ROW_START = "EDIT_FORM_ROW_START";

export const FAIL_EDIT_FORM = "FAIL_EDIT_FORM";
export const CURRENT_USER_EDIT_FORM = "CURRENT_USER_EDIT_FORM";
export const UPDATE_FORM_DATA_START = "UPDATE_FORM_DATA_START";

// Prefix actionTypes

export const PREFIX_GET_DATA = "PREFIX_GET_DATA";
export const PREFIX_SET_DATA = "PREFIX_SET_DATA";
export const PREFIX_FAIL_DATA = "PREFIX_FAIL_DATA";
export const DELETE_PREFIX_FAIL = "DELETE_PREFIX_FAIL";
export const POST_PREFIX_DATA = "POST_PREFIX_DATA";
export const POST_PREFIX_DATA_START = "POST_PREFIX_DATA_START";
export const POST_PREFIX_DATA_FAIL = "POST_PREFIX_DATA_FAIL";
export const EDIT_PREFIX_ROW_START = "EDIT_PREFIX_ROW_START";

export const FAIL_EDIT_PREFIX = "FAIL_EDIT_PREFIX";
export const CURRENT_USER_EDIT_PREFIX = "CURRENT_USER_EDIT_PREFIX";
export const UPDATE_PREFIX_DATA_START = "UPDATE_PREFIX_DATA_START";
export const PREFIX_LOADING = "PREFIX_LOADING";
export const PREFIX_POST_LOADING = "PREFIX_POST_LOADING";
export const PREFIX_UPDATE_LOADING = "PREFIX_UPDATE_LOADING";

// Account Group actionTypes

export const ACCOUNT_GROUP_GET_DATA = "ACCOUNT_GROUP_GET_DATA";
export const ACCOUNT_GROUP_SET_DATA = "ACCOUNT_GROUP_SET_DATA";
export const ACCOUNT_GROUP_FAIL_DATA = "ACCOUNT_GROUP_FAIL_DATA";
export const DELETE_ACCOUNT_GROUP_FAIL = "DELETE_ACCOUNT_GROUP_FAIL";
export const POST_ACCOUNT_GROUP_DATA = "POST_ACCOUNT_GROUP_DATA";
export const POST_ACCOUNT_GROUP_DATA_START = "POST_ACCOUNT_GROUP_DATA_START";
export const POST_ACCOUNT_GROUP_DATA_FAIL = "POST_ACCOUNT_GROUP_DATA_FAIL";
export const EDIT_ACCOUNT_GROUP_ROW_START = "EDIT_ACCOUNT_GROUP_ROW_START";

export const FAIL_EDIT_ACCOUNT_GROUP = "FAIL_EDIT_ACCOUNT_GROUP";
export const CURRENT_USER_EDIT_ACCOUNT_GROUP =
  "CURRENT_USER_EDIT_ACCOUNT_GROUP";
export const UPDATE_ACCOUNT_GROUP_DATA_START =
  "UPDATE_ACCOUNT_GROUP_DATA_START";

// Account Name actionTypes

export const ACCOUNT_NAME_GET_DATA = "ACCOUNT_NAME_GET_DATA";
export const ACCOUNT_NAME_SET_DATA = "ACCOUNT_NAME_SET_DATA";
export const ACCOUNT_NAME_FAIL_DATA = "ACCOUNT_NAME_FAIL_DATA";
export const DELETE_ACCOUNT_NAME_FAIL = "DELETE_ACCOUNT_NAME_FAIL";
export const POST_ACCOUNT_NAME_DATA = "POST_ACCOUNT_NAME_DATA";
export const POST_ACCOUNT_NAME_DATA_START = "POST_ACCOUNT_NAME_DATA_START";
export const POST_ACCOUNT_NAME_DATA_FAIL = "POST_ACCOUNT_NAME_DATA_FAIL";
export const EDIT_ACCOUNT_NAME_ROW_START = "EDIT_ACCOUNT_NAME_ROW_START";

export const FAIL_EDIT_ACCOUNT_NAME = "FAIL_EDIT_ACCOUNT_NAME";

export const UPDATE_ACCOUNT_NAME_DATA_START = "UPDATE_ACCOUNT_NAME_DATA_START";

// Item Group actionTypes

export const ITEM_GROUP_GET_DATA = "ITEM_GROUP_GET_DATA";
export const ITEM_GROUP_SET_DATA = "ITEM_GROUP_SET_DATA";
export const ITEM_GROUP_FAIL_DATA = "ITEM_GROUP_FAIL_DATA";
export const DELETE_ITEM_GROUP_FAIL = "DELETE_ITEM_GROUP_FAIL";
export const POST_ITEM_GROUP_DATA = "POST_ITEM_GROUP_DATA";
export const POST_ITEM_GROUP_DATA_START = "POST_ITEM_GROUP_DATA_START";
export const POST_ITEM_GROUP_DATA_FAIL = "POST_ITEM_GROUP_DATA_FAIL";
export const EDIT_ITEM_GROUP_ROW_START = "EDIT_ITEM_GROUP_ROW_START";

export const FAIL_EDIT_ITEM_GROUP = "FAIL_EDIT_ITEM_GROUP";
export const CURRENT_USER_EDIT_ITEM_GROUP = "CURRENT_USER_EDIT_ITEM_GROUP";
export const UPDATE_ITEM_GROUP_DATA_START = "UPDATE_ITEM_GROUP_DATA_START";

// ITEM Name actionTypes

export const ITEM_NAME_GET_DATA = "ITEM_NAME_GET_DATA";
export const ITEM_NAME_SET_DATA = "ITEM_NAME_SET_DATA";
export const ITEM_NAME_FAIL_DATA = "ITEM_NAME_FAIL_DATA";
export const DELETE_ITEM_NAME_FAIL = "DELETE_ITEM_NAME_FAIL";
export const POST_ITEM_NAME_DATA = "POST_ITEM_NAME_DATA";
export const POST_ITEM_NAME_DATA_START = "POST_ITEM_NAME_DATA_START";
export const POST_ITEM_NAME_DATA_FAIL = "POST_ITEM_NAME_DATA_FAIL";
export const EDIT_ITEM_NAME_ROW_START = "EDIT_ITEM_NAME_ROW_START";

export const FAIL_EDIT_ITEM_NAME = "FAIL_EDIT_ITEM_NAME";

export const UPDATE_ITEM_NAME_DATA_START = "UPDATE_ITEM_NAME_DATA_START";

// ITEM Units actionTypes

export const ITEM_UNITS_GET_DATA = "ITEM_UNITS_GET_DATA";
export const ITEM_UNITS_SET_DATA = "ITEM_UNITS_SET_DATA";
export const ITEM_UNITS_FAIL_DATA = "ITEM_UNITS_FAIL_DATA";
export const DELETE_ITEM_UNITS_FAIL = "DELETE_ITEM_UNITS_FAIL";
export const POST_ITEM_UNITS_DATA = "POST_ITEM_UNITS_DATA";
export const POST_ITEM_UNITS_DATA_START = "POST_ITEM_UNITS_DATA_START";
export const POST_ITEM_UNITS_DATA_FAIL = "POST_ITEM_UNITS_DATA_FAIL";
export const EDIT_ITEM_UNITS_ROW_START = "EDIT_ITEM_UNITS_ROW_START";

export const FAIL_EDIT_ITEM_UNITS = "FAIL_EDIT_ITEM_UNITS";

export const UPDATE_ITEM_UNITS_DATA_START = "UPDATE_ITEM_UNITS_DATA_START";

// UserMaster actionTypes

export const USER_MASTER_GET_DATA = "USER_MASTER_GET_DATA";
export const USER_MASTER_SET_DATA = "USER_MASTER_SET_DATA";
export const USER_MASTER_FAIL_DATA = "USER_MASTER_FAIL_DATA";
export const DELETE_USER_MASTER_FAIL = "DELETE_USER_MASTER_FAIL";
export const POST_USER_MASTER_DATA = "POST_USER_MASTER_DATA";
export const POST_USER_MASTER_DATA_START = "POST_USER_MASTER_DATA_START";
export const POST_USER_MASTER_DATA_FAIL = "POST_USER_MASTER_DATA_FAIL";
export const EDIT_USER_MASTER_ROW_START = "EDIT_USER_MASTER_ROW_START";

export const FAIL_EDIT_USER_MASTER = "FAIL_EDIT_USER_MASTER";
export const CURRENT_USER_EDIT_USER_MASTER = "CURRENT_USER_EDIT_USER_MASTER";
export const UPDATE_USER_MASTER_DATA_START = "UPDATE_USER_MASTER_DATA_START";

// / Pages actionTypes

export const PAGE_GET_DATA = "PAGE_GET_DATA";
export const PAGE_SET_DATA = "PAGE_SET_DATA";
export const PAGE_FAIL_DATA = "PAGE_FAIL_DATA";
export const DELETE_PAGE_FAIL = "DELETE_PAGE_FAIL";
export const POST_PAGE_DATA = "POST_PAGE_DATA";
export const POST_PAGE_DATA_START = "POST_PAGE_DATA_START";
export const POST_PAGE_DATA_FAIL = "POST_PAGE_DATA_FAIL";
export const POST_PAGE_DATA_SUCCESS = "POST_PAGE_DATA_SUCCESS";

export const UPDATE_PAGE_DATA_START = "UPDATE_PAGE_DATA_START";
export const PAGE_LOADING = "PAGE_LOADING";
export const PAGE_EDIT_SET_DATA = "PAGE_EDIT_SET_DATA";
export const PAGE_EDIT_FAIL_DATA = "PAGE_EDIT_FAIL_DATA";

//  Rights actionTypes

export const RIGHT_GET_DATA = "RIGHT_GET_DATA";
export const RIGHT_SET_DATA = "RIGHT_SET_DATA";
export const RIGHT_FAIL_DATA = "RIGHT_FAIL_DATA";
export const DELETE_RIGHT_FAIL = "DELETE_RIGHT_FAIL";
export const POST_RIGHT_DATA = "POST_RIGHT_DATA";
export const POST_RIGHT_DATA_START = "POST_RIGHT_DATA_START";
export const POST_RIGHT_DATA_FAIL = "POST_RIGHT_DATA_FAIL";
export const POST_RIGHT_DATA_SUCCESS = "POST_RIGHT_DATA_SUCCESS";

export const UPDATE_RIGHT_DATA_START = "UPDATE_RIGHT_DATA_START";
export const RIGHT_LOADING = "RIGHT_LOADING";
export const RIGHT_EDIT_SET_DATA = "RIGHT_EDIT_SET_DATA";
export const RIGHT_EDIT_FAIL_DATA = "RIGHT_EDIT_FAIL_DATA";

//  details actionTypes

export const DETAILS_GET_DATA = "DETAILS_GET_DATA";
export const DETAILS_SET_DATA = "DETAILS_SET_DATA";
export const DETAILS_FAIL_DATA = "DETAILS_FAIL_DATA";
export const DELETE_DETAILS_FAIL = "DELETE_DETAILS_FAIL";
export const POST_DETAILS_DATA = "POST_DETAILS_DATA";
export const POST_DETAILS_DATA_START = "POST_DETAILS_DATA_START";
export const POST_DETAILS_DATA_FAIL = "POST_DETAILS_DATA_FAIL";
export const POST_DETAILS_DATA_SUCCESS = "POST_DETAILS_DATA_SUCCESS";

export const UPDATE_DETAILS_DATA_START = "UPDATE_DETAILS_DATA_START";

export const DETAILS_EDIT_SET_DATA = "DETAILS_EDIT_SET_DATA";
export const DETAILS_EDIT_FAIL_DATA = "DETAILS_EDIT_FAIL_DATA";
export const DETAILS_LOADING = "DETAILS_LOADING";
export const DETAILS_POST_LOADING = "DETAILS_POST_LOADING";
export const DETAILS_POST_SUCCESS = "DETAILS_POST_SUCCESS";
export const DETAILS_UPDATE_LOADING = "DETAILS_UPDATE_LOADING";

//  Process actionTypes

export const PROCESS_GET_DATA = "PROCESS_GET_DATA";
export const PROCESS_SET_DATA = "PROCESS_SET_DATA";
export const PROCESS_FAIL_DATA = "PROCESS_FAIL_DATA";
export const DELETE_PROCESS_FAIL = "DELETE_PROCESS_FAIL";
export const POST_PROCESS_DATA = "POST_PROCESS_DATA";
export const POST_PROCESS_DATA_START = "POST_PROCESS_DATA_START";
export const POST_PROCESS_DATA_FAIL = "POST_PROCESS_DATA_FAIL";
export const POST_PROCESS_DATA_SUCCESS = "POST_PROCESS_DATA_SUCCESS";

export const UPDATE_PROCESS_DATA_START = "UPDATE_PROCESS_DATA_START";

export const PROCESS_EDIT_SET_DATA = "PROCESS_EDIT_SET_DATA";
export const PROCESS_EDIT_FAIL_DATA = "PROCESS_EDIT_FAIL_DATA";
export const PROCESS_LOADING = "PROCESS_LOADING";
export const PROCESS_POST_LOADING = "PROCESS_POST_LOADING";
export const PROCESS_POST_SUCCESS = "PROCESS_POST_SUCCESS";
export const PROCESS_UPDATE_LOADING = "PROCESS_UPDATE_LOADING";

// Breakdown Maintenance Record actionTypes

export const BREAK_MAIN_RECORD_GET_DATA = "BREAK_MAIN_RECORD_GET_DATA";
export const BREAK_MAIN_RECORD_SET_DATA = "BREAK_MAIN_RECORD_SET_DATA";
export const BREAK_MAIN_RECORD_FAIL_DATA = "BREAK_MAIN_RECORD_FAIL_DATA";
export const DELETE_BREAK_MAIN_RECORD_FAIL = "DELETE_BREAK_MAIN_RECORD_FAIL";
export const POST_BREAK_MAIN_RECORD_DATA = "POST_BREAK_MAIN_RECORD_DATA";
export const POST_BREAK_MAIN_RECORD_DATA_START =
  "POST_BREAK_MAIN_RECORD_DATA_START";
export const POST_BREAK_MAIN_RECORD_DATA_FAIL =
  "POST_BREAK_MAIN_RECORD_DATA_FAIL";
export const POST_BREAK_MAIN_RECORD_DATA_SUCCESS =
  "POST_BREAK_MAIN_RECORD_DATA_SUCCESS";

export const UPDATE_BREAK_MAIN_RECORD_DATA_START =
  "UPDATE_BREAK_MAIN_RECORD_DATA_START";

export const BREAK_MAIN_RECORD_EDIT_SET_DATA =
  "BREAK_MAIN_RECORD_EDIT_SET_DATA";
export const BREAK_MAIN_RECORD_EDIT_FAIL_DATA =
  "BREAK_MAIN_RECORD_EDIT_FAIL_DATA";
export const BREAK_MAIN_RECORD_LOADING = "BREAK_MAIN_RECORD_LOADING";
export const BREAK_MAIN_RECORD_POST_LOADING = "BREAK_MAIN_RECORD_POST_LOADING";
export const BREAK_MAIN_RECORD_POST_SUCCESS = "BREAK_MAIN_RECORD_POST_SUCCESS";
export const BREAK_MAIN_RECORD_UPDATE_LOADING =
  "BREAK_MAIN_RECORD_UPDATE_LOADING";

//  Enquiries Forms Sales actionTypes

export const ENQUIRIES_FORM_GET_DATA = "ENQUIRIES_FORM_GET_DATA";
export const ENQUIRIES_FORM_SET_DATA = "ENQUIRIES_FORM_SET_DATA";
export const ENQUIRIES_FORM_FAIL_DATA = "ENQUIRIES_FORM_FAIL_DATA";
export const DELETE_ENQUIRIES_FORM_FAIL = "DELETE_ENQUIRIES_FORM_FAIL";
export const POST_ENQUIRIES_FORM_DATA = "POST_ENQUIRIES_FORM_DATA";
export const POST_ENQUIRIES_FORM_DATA_START = "POST_ENQUIRIES_FORM_DATA_START";
export const POST_ENQUIRIES_FORM_DATA_FAIL = "POST_ENQUIRIES_FORM_DATA_FAIL";
export const POST_ENQUIRIES_FORM_DATA_SUCCESS =
  "POST_ENQUIRIES_FORM_DATA_SUCCESS";

export const UPDATE_ENQUIRIES_FORM_DATA_START =
  "UPDATE_ENQUIRIES_FORM_DATA_START";

export const ENQUIRIES_FORM_EDIT_SET_DATA = "ENQUIRIES_FORM_EDIT_SET_DATA";
export const ENQUIRIES_FORM_EDIT_FAIL_DATA = "ENQUIRIES_FORM_EDIT_FAIL_DATA";
export const ENQUIRIES_FORM_LOADING = "ENQUIRIES_FORM_LOADING";
export const ENQUIRIES_FORM_POST_LOADING = "ENQUIRIES_FORM_POST_LOADING";
export const ENQUIRIES_FORM_POST_SUCCESS = "ENQUIRIES_FORM_POST_SUCCESS";
export const ENQUIRIES_FORM_UPDATE_LOADING = "ENQUIRIES_FORM_UPDATE_LOADING";

//  Production Planning Cf Production actionTypes

export const PROD_PLAN_CF_GET_DATA = "PROD_PLAN_CF_GET_DATA";
export const PROD_PLAN_CF_SET_DATA = "PROD_PLAN_CF_SET_DATA";
export const PROD_PLAN_CF_FAIL_DATA = "PROD_PLAN_CF_FAIL_DATA";
export const DELETE_PROD_PLAN_CF_FAIL = "DELETE_PROD_PLAN_CF_FAIL";
export const POST_PROD_PLAN_CF_DATA = "POST_PROD_PLAN_CF_DATA";
export const POST_PROD_PLAN_CF_DATA_START = "POST_PROD_PLAN_CF_DATA_START";
export const POST_PROD_PLAN_CF_DATA_FAIL = "POST_PROD_PLAN_CF_DATA_FAIL";
export const POST_PROD_PLAN_CF_DATA_SUCCESS = "POST_PROD_PLAN_CF_DATA_SUCCESS";

export const UPDATE_PROD_PLAN_CF_DATA_START = "UPDATE_PROD_PLAN_CF_DATA_START";

export const PROD_PLAN_CF_EDIT_SET_DATA = "PROD_PLAN_CF_EDIT_SET_DATA";
export const PROD_PLAN_CF_EDIT_FAIL_DATA = "PROD_PLAN_CF_EDIT_FAIL_DATA";
export const PROD_PLAN_CF_LOADING = "PROD_PLAN_CF_LOADING";
export const PROD_PLAN_CF_POST_LOADING = "PROD_PLAN_CF_POST_LOADING";
export const PROD_PLAN_CF_POST_SUCCESS = "PROD_PLAN_CF_POST_SUCCESS";
export const PROD_PLAN_CF_UPDATE_LOADING = "PROD_PLAN_CF_UPDATE_LOADING";
